apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-foo
spec:
  resources:
    - name: git-repo
      type: git
    - name: os-image
      type: image

  tasks:
    - name: build-s2i
      taskRef:
        name: s2i-java-11
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: os-image
      params:
        - name: TLSVERIFY
          value: "false"
    - name: apply-api-manifests
      taskRef:
        name: apply-foo
      resources:
        inputs:
          - name: source
            resource: git-repo
      runAfter:
        - build-s2i
