---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/vgokul984/foo.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: os-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/development/tknfoo:latest
---
